name: EmptyChunkUnsaver
description: Save disk space by cancelling
version: '${project.version}'
main: ru.whbex.ecu.Main
api-version: 1.19
commands:
  ecu:
    description: EmptyChunkUnsaver main command
    permission: ecu.command

