name: EmptyChunkUnsaver
description: Shrink world size by cancelling unchanged chunk save
version: '${project.version}'
main: ru.whbex.ecu.Main
api-version: 1.19
commands:
  ecu:
    description: EmptyChunkUnsaver main command
    permission: ecu.command

